/* this file was generated by vite-svg-sprite-wrapper */
export type SvgIcons = 'alien' | 'arrow-circle-up-right' | 'bird' | 'carret-up-down' | 'cat' | 'chevron-left' | 'dog' | 'fish' | 'horse' | 'house-line' | 'info' | 'nouvet' | 'package' | 'paw-print' | 'rabbit' | 'rodent' | 'scroll' | 'stack'
